INSERT INTO categories (name, apple_id) VALUES ("Book", "25469");
INSERT INTO categories (name, apple_id) VALUES ("Business", "25130");
INSERT INTO categories (name, apple_id) VALUES ("Education", "25131");
INSERT INTO categories (name, apple_id) VALUES ("Entertainment", "25132");
INSERT INTO categories (name, apple_id) VALUES ("Finance", "25133");
INSERT INTO categories (name, apple_id) VALUES ("Games", "25134");
INSERT INTO categories (name, apple_id) VALUES ("Healthcare & Fitness", "25135");
INSERT INTO categories (name, apple_id) VALUES ("Lifestyle", "25136");
INSERT INTO categories (name, apple_id) VALUES ("Medical", "26320");
INSERT INTO categories (name, apple_id) VALUES ("Music", "25137");
INSERT INTO categories (name, apple_id) VALUES ("Navigation", "25138");
INSERT INTO categories (name, apple_id) VALUES ("News", "25139");
INSERT INTO categories (name, apple_id) VALUES ("Photography", "25140");
INSERT INTO categories (name, apple_id) VALUES ("Productivity", "25141");
INSERT INTO categories (name, apple_id) VALUES ("Reference", "25142");
INSERT INTO categories (name, apple_id) VALUES ("Social Networking", "25143");
INSERT INTO categories (name, apple_id) VALUES ("Sports", "25144");
INSERT INTO categories (name, apple_id) VALUES ("Travel", "25145");
INSERT INTO categories (name, apple_id) VALUES ("Utilities", "25146");
INSERT INTO categories (name, apple_id) VALUES ("Weather", "25147");
INSERT INTO categories (name, apple_id) VALUES ("Top", "25129");