INSERT INTO stores (apple_id, name) VALUES ("143441", "United States");
INSERT INTO stores (apple_id, name) VALUES ("143505", "Argentina");
INSERT INTO stores (apple_id, name) VALUES ("143524", "Armenia");
INSERT INTO stores (apple_id, name) VALUES ("143460", "Australia");
INSERT INTO stores (apple_id, name) VALUES ("143446", "België/Belgique");
INSERT INTO stores (apple_id, name) VALUES ("143525", "Botswana");
INSERT INTO stores (apple_id, name) VALUES ("143503", "Brazil");
INSERT INTO stores (apple_id, name) VALUES ("143526", "Bulgaria");
INSERT INTO stores (apple_id, name) VALUES ("143455", "Canada");
INSERT INTO stores (apple_id, name) VALUES ("143483", "Chile");
INSERT INTO stores (apple_id, name) VALUES ("143465", "China");
INSERT INTO stores (apple_id, name) VALUES ("143501", "Colombia");
INSERT INTO stores (apple_id, name) VALUES ("143495", "Costa Rica");
INSERT INTO stores (apple_id, name) VALUES ("143494", "Croatia");
INSERT INTO stores (apple_id, name) VALUES ("143489", "Czech Republic");
INSERT INTO stores (apple_id, name) VALUES ("143458", "Denmark");
INSERT INTO stores (apple_id, name) VALUES ("143443", "Deutschland");
INSERT INTO stores (apple_id, name) VALUES ("143508", "Dominican Republic");
INSERT INTO stores (apple_id, name) VALUES ("143509", "Ecuador");
INSERT INTO stores (apple_id, name) VALUES ("143516", "Egypt");
INSERT INTO stores (apple_id, name) VALUES ("143506", "El Salvador");
INSERT INTO stores (apple_id, name) VALUES ("143454", "España");
INSERT INTO stores (apple_id, name) VALUES ("143518", "Estonia");
INSERT INTO stores (apple_id, name) VALUES ("143447", "Finland");
INSERT INTO stores (apple_id, name) VALUES ("143442", "France");
INSERT INTO stores (apple_id, name) VALUES ("143448", "Greece");
INSERT INTO stores (apple_id, name) VALUES ("143504", "Guatemala");
INSERT INTO stores (apple_id, name) VALUES ("143510", "Honduras");
INSERT INTO stores (apple_id, name) VALUES ("143463", "Hong Kong");
INSERT INTO stores (apple_id, name) VALUES ("143482", "Hungary");
INSERT INTO stores (apple_id, name) VALUES ("143467", "India");
INSERT INTO stores (apple_id, name) VALUES ("143476", "Indonesia");
INSERT INTO stores (apple_id, name) VALUES ("143449", "Ireland");
INSERT INTO stores (apple_id, name) VALUES ("143491", "Israel");
INSERT INTO stores (apple_id, name) VALUES ("143450", "Italia");
INSERT INTO stores (apple_id, name) VALUES ("143511", "Jamaica");
INSERT INTO stores (apple_id, name) VALUES ("143528", "Jordan");
INSERT INTO stores (apple_id, name) VALUES ("143517", "Kazakhstan");
INSERT INTO stores (apple_id, name) VALUES ("143529", "Kenya");
INSERT INTO stores (apple_id, name) VALUES ("143466", "Korea");
INSERT INTO stores (apple_id, name) VALUES ("143493", "Kuwait");
INSERT INTO stores (apple_id, name) VALUES ("143519", "Latvia");
INSERT INTO stores (apple_id, name) VALUES ("143497", "Lebanon");
INSERT INTO stores (apple_id, name) VALUES ("143520", "Lithuania");
INSERT INTO stores (apple_id, name) VALUES ("143451", "Luxembourg");
INSERT INTO stores (apple_id, name) VALUES ("143515", "Macau");
INSERT INTO stores (apple_id, name) VALUES ("143530", "Macedonia");
INSERT INTO stores (apple_id, name) VALUES ("143531", "Madagascar");
INSERT INTO stores (apple_id, name) VALUES ("143473", "Malaysia");
INSERT INTO stores (apple_id, name) VALUES ("143532", "Mali");
INSERT INTO stores (apple_id, name) VALUES ("143533", "Mauritius");
INSERT INTO stores (apple_id, name) VALUES ("143468", "México");
INSERT INTO stores (apple_id, name) VALUES ("143452", "Nederland");
INSERT INTO stores (apple_id, name) VALUES ("143461", "New Zealand");
INSERT INTO stores (apple_id, name) VALUES ("143512", "Nicaragua");
INSERT INTO stores (apple_id, name) VALUES ("143534", "Niger");
INSERT INTO stores (apple_id, name) VALUES ("143457", "Norway");
INSERT INTO stores (apple_id, name) VALUES ("143445", "Österreich");
INSERT INTO stores (apple_id, name) VALUES ("143477", "Pakistan");
INSERT INTO stores (apple_id, name) VALUES ("143485", "Panamá");
INSERT INTO stores (apple_id, name) VALUES ("143513", "Paraguay");
INSERT INTO stores (apple_id, name) VALUES ("143507", "Perú");
INSERT INTO stores (apple_id, name) VALUES ("143474", "Philippines");
INSERT INTO stores (apple_id, name) VALUES ("143478", "Poland");
INSERT INTO stores (apple_id, name) VALUES ("143453", "Portugal");
INSERT INTO stores (apple_id, name) VALUES ("143498", "Qatar");
INSERT INTO stores (apple_id, name) VALUES ("143521", "Republic of Malta");
INSERT INTO stores (apple_id, name) VALUES ("143523", "Republic of Moldova");
INSERT INTO stores (apple_id, name) VALUES ("143487", "Romania");
INSERT INTO stores (apple_id, name) VALUES ("143469", "Russia");
INSERT INTO stores (apple_id, name) VALUES ("143479", "Saudi Arabia");
INSERT INTO stores (apple_id, name) VALUES ("143459", "Schweiz/Suisse");
INSERT INTO stores (apple_id, name) VALUES ("143535", "Senegal");
INSERT INTO stores (apple_id, name) VALUES ("143464", "Singapore");
INSERT INTO stores (apple_id, name) VALUES ("143496", "Slovakia");
INSERT INTO stores (apple_id, name) VALUES ("143499", "Slovenia");
INSERT INTO stores (apple_id, name) VALUES ("143472", "South Africa");
INSERT INTO stores (apple_id, name) VALUES ("143486", "Sri Lanka");
INSERT INTO stores (apple_id, name) VALUES ("143456", "Sweden");
INSERT INTO stores (apple_id, name) VALUES ("143470", "Taiwan");
INSERT INTO stores (apple_id, name) VALUES ("143475", "Thailand");
INSERT INTO stores (apple_id, name) VALUES ("143536", "Tunisia");
INSERT INTO stores (apple_id, name) VALUES ("143480", "Turkey");
INSERT INTO stores (apple_id, name) VALUES ("143537", "Uganda");
INSERT INTO stores (apple_id, name) VALUES ("143481", "United Arab Emirates");
INSERT INTO stores (apple_id, name) VALUES ("143444", "United Kingdom");
INSERT INTO stores (apple_id, name) VALUES ("143514", "Uruguay");
INSERT INTO stores (apple_id, name) VALUES ("143502", "Venezuela");
INSERT INTO stores (apple_id, name) VALUES ("143471", "Vietnam");
INSERT INTO stores (apple_id, name) VALUES ("143462", "Japan");